### ISSUE TITLE
Negative cases in dataset

### ISSUE THREAD

**Issue by luizfcp** [Covid19R/coronavirus#1]
First of all, congratulations on the package.

I'm developing a dashboard in shiny with some visualizations and I came across negative values ​​in the data set.

Why negative cases?

`coronavirus[coronavirus$cases==-268,]`

![image](https://user-images.githubusercontent.com/32424647/78463556-7bb6f480-76b4-11ea-91e9-62f0d15242a6.png)

**Comment by RamiKrispin** [comment]
Hi @luizfcp, 

Negative values, as in this case, appear in the raw data on John Hopkins data. This will occur when the cumulative value on one day is dropping with respect to the previous day. This could be due to policy changes in a specific country (for example the definition of recovery case) or updates in the calculation due to new information. 

Hope that makes sense
Rami
